# .github/workflows/build.yml
name: Build Ionic App

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npx ionic build --project Angular-FK13
      - run: npx cap sync android
      - run: cd android && ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
